resources:
  - ../../base  

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: forgerock-ig  
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: forgerock-ig-dev
      spec:
        replicas: 2
