apiVersion: v1
kind: Service
metadata:
  name: forgerock-ig-service
  labels:
    app: forgerock-ig
spec:
  selector:
    app: forgerock-ig
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
