apiVersion: v1
kind: Service
metadata:
  name: forgerock-ig-service
spec:
  selector:
    app: forgerock-ig
   ports:
    - protocol: TCP
      port: 8080        
      targetPort: 8080   
  type: NodePort       
