apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgerock-ig 
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: forgerock-ig 
        image: shiv512/forgerock-ig:latest
